# Generated by Django 5.2.3 on 2025-06-21 14:44

import api.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('cpf_titular', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF do Titular da UC')),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('endereco', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaturaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_titular', models.CharField(max_length=14)),
                ('ucs_encontradas', models.JSONField(default=list)),
                ('faturas_encontradas', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatura_logs', to='api.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UnidadeConsumidora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Residencial', 'Residencial'), ('Comercial', 'Comercial'), ('Industrial', 'Industrial'), ('Rural', 'Rural')], default='Residencial', max_length=20)),
                ('data_vigencia_inicio', models.DateField(default=django.utils.timezone.now)),
                ('data_vigencia_fim', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_consumidoras', to='api.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FaturaTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Concluída'), ('failed', 'Falhou')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatura_tasks', to='api.customer')),
                ('unidade_consumidora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatura_tasks', to='api.unidadeconsumidora')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False)),
                ('mes_referencia', models.DateField()),
                ('arquivo', models.FileField(max_length=500, upload_to=api.models.fatura_upload_path)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('vencimento', models.DateField(blank=True, null=True)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='api.customer')),
                ('unidade_consumidora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faturas', to='api.unidadeconsumidora')),
            ],
            options={
                'ordering': ['-mes_referencia'],
            },
        ),
        migrations.AddConstraint(
            model_name='unidadeconsumidora',
            constraint=models.UniqueConstraint(condition=models.Q(('data_vigencia_fim__isnull', True)), fields=('customer', 'codigo'), name='unique_active_uc_per_customer'),
        ),
        migrations.AlterUniqueTogether(
            name='fatura',
            unique_together={('unidade_consumidora', 'mes_referencia')},
        ),
    ]
