# Generated by Django 5.2.2 on 2025-06-21 16:10

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fatura',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='fatura',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='arquivo',
            field=models.FileField(max_length=500, upload_to=api.models.upload_to),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('IN_PROGRESS', 'Em Progresso'), ('SUCCESS', 'Sucesso'), ('FAILURE', 'Falha')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('details', models.TextField(blank=True, help_text='Detalhes sobre a execução da tarefa, como logs ou mensagens de erro.', null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
