# Generated by Django 5.2.2 on 2025-06-05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadeConsumidora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('Residencial', 'Residencial'), ('Comercial', 'Comercial'), ('Industrial', 'Industrial'), ('Rural', 'Rural')], default='Residencial', max_length=20)),
                ('data_vigencia_inicio', models.DateField(default=django.utils.timezone.now)),
                ('data_vigencia_fim', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_consumidoras', to='api.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='unidadeconsumidora',
            constraint=models.UniqueConstraint(condition=models.Q(('data_vigencia_fim__isnull', True)), fields=('customer', 'codigo'), name='unique_active_uc_per_customer'),
        ),
    ]