# Generated by Django 5.2.2 on 2025-06-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_fatura_options_alter_fatura_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fatura',
            options={'ordering': ['-mes_referencia']},
        ),
        migrations.AlterUniqueTogether(
            name='fatura',
            unique_together={('unidade_consumidora', 'mes_referencia')},
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
