# Generated by Django 5.2.3 on 2025-06-21 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_customer_updates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faturatask',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='faturatask',
            name='unidade_consumidora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fatura_tasks', to='api.unidadeconsumidora'),
        ),
    ]
